/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBtn: typeof import('./src/components/AppBtn.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppInput: typeof import('./src/components/AppInput.vue')['default']
    AppStatCard: typeof import('./src/components/AppStatCard.vue')['default']
    CategoriesTable: typeof import('./src/components/expense-categories/CategoriesTable.vue')['default']
    CategoryFormDialog: typeof import('./src/components/expense-categories/CategoryFormDialog.vue')['default']
    CategoryStatsCard: typeof import('./src/components/expense-categories/CategoryStatsCard.vue')['default']
    DashboardStats: typeof import('./src/components/dashboard/DashboardStats.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RecentTransactions: typeof import('./src/components/dashboard/RecentTransactions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavingsGoals: typeof import('./src/components/dashboard/SavingsGoals.vue')['default']
    SessionExpiryDialog: typeof import('./src/components/ui/SessionExpiryDialog.vue')['default']
    UserEditDialog: typeof import('./src/components/dashboard/UserEditDialog.vue')['default']
    UsersTable: typeof import('./src/components/dashboard/UsersTable.vue')['default']
  }
}
