/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBtn: typeof import('./src/components/AppBtn.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppInput: typeof import('./src/components/AppInput.vue')['default']
    AppStatCard: typeof import('./src/components/AppStatCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
